import js from "@eslint/js";

export default [
  js.configs.recommended,
  {
    languageOptions: {
      ecmaVersion: 2024,
      sourceType: "module",
      globals: {
        console: "readonly",
        process: "readonly",
        Buffer: "readonly",
        setTimeout: "readonly",
        clearTimeout: "readonly",
        structuredClone: "readonly",
        navigator: "readonly",
        document: "readonly",
        window: "readonly",
        HTMLElement: "readonly",
        Event: "readonly",
        CustomEvent: "readonly",
        URL: "readonly",
        URLSearchParams: "readonly",
        fetch: "readonly",
        Worker: "readonly",
        self: "readonly",
        postMessage: "readonly",
        onmessage: "readonly",
        AbortController: "readonly",
        performance: "readonly",
        crypto: "readonly",
        TextEncoder: "readonly",
        atob: "readonly",
        btoa: "readonly",
        Blob: "readonly",
        HTMLInputElement: "readonly",
        HTMLTextAreaElement: "readonly",
        localStorage: "readonly",
        sessionStorage: "readonly",
        indexedDB: "readonly",
        XMLHttpRequest: "readonly",
        WebSocket: "readonly",
        navigator_sendBeacon: "readonly",
      },
    },
    rules: {
      "no-unused-vars": ["error", { argsIgnorePattern: "^_" }],
      "no-console": "off",
    },
  },
  {
    ignores: ["node_modules/**", "coverage/**", ".cache/**"],
  },
];
